output_directory: "output"

#youtube:
#  url: "https://www.youtube.com/watch?v=4cm9PMNikXM"
#  language: "bn"

youtube:
  url: "https://www.youtube.com/watch?v=q9jixKv4h2I"
  language: "en"

models:
  transcript: "llama3.2:3b"
  validator: "llama3.2:3b"