[tool.poetry]
name = "essentialprojects"
version = "0.1.0"
description = ""
authors = ["Arghya Bandyopadhyay <arghya.bandyopadhyay.official1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.15"
youtube-transcript-api = "^1.2.4"
ollama = "^0.6.2"
yt-dlp = "^2026.7.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
